steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c2:$COMMIT_SHA', '.']
  
  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c2:$COMMIT_SHA']
  
  # Update the GKE deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/container2-deployment', 'container2=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c2:$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=clod-a3-cluster'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-a3/cloud-a3-c2:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY